### ISSUE TITLE
Feature request: Add CompletionProvider

### ISSUE THREAD

**Issue by vchirikov** [daveoftheparty/speedy-moq#42]
Hi, thanks for the extension.
Could you add a CompletionProvider like https://github.com/MrLuje/Mocking.Helpers in your extension?

**Comment by daveoftheparty** [comment]
Hmm... I may have to download Visual Studio Community to give that extension a try, I haven't used Visual Studio in some time. 

From what I can tell given the screenshots on Mocking.Helpers, however, Speedy Moq is trying to solve a different problem-- I don't **_want_** to type out mocks character by character, substitution/completion by substitution :D 

I want to focus on writing my test logic, and not the <>><>()() ugliness of the (completely necessary) mocking libraries.

I'm not quite ready to put the "wontfix" label on this issue, or close it, yet, but I'm leaning that direction. I'll give it a little time to think through.

**Comment by daveoftheparty** [comment]
I've had a couple of days to think about this, and the more I think about it, the less useful I think code completion would be in this extension. I thank you for your feedback!
